spring.application.name=cardapio
#--- Postgres connection
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:default_value}
#--- Optional
spring.jpa.show-sql=true
#--- To prevent conflicts with fly_way
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true